### ISSUE TITLE
WER frozen while training 

### ISSUE THREAD

**Issue by jjsr** [FactoDeepLearning/VerticalAttentionOCR#11]
Hi, I am training the model from scratch . I have enabled the 'use_ddp' option in training parameters. Rest is default as given. I am on 1672 epoch CTC loss is 5.669 CER is 0.7126 and WER is 1.0072(it's kind of frozen) diff_length is 0.422. My last best epoch is 1018. I think I may be doing something wrong. May anyone please help. Thanking in advance. Should I turn off DDP and run it again. Please Please help

**Comment by jjsr** [comment]
Thanks a lot for answering sir. Is default parameters for  training of file - "main_pg_va.py" are same to produce the results of the paper
 ` "training_params": {`
            "output_folder": "van_iam_paragraph_learned_stop",  # folder names for logs and weights  
               "max_nb_epochs": 5000,  # max number of epochs for the training
               "max_training_time": 3600 * (24 + 23),  # max training time limit (in seconds)
            "load_epoch": "best",  # ["best", "last"], to load weights from best epoch or last trained epoch
            "interval_save_weights": None,  # None: keep best and last only
            "batch_size": 8,  # mini-batch size per GPU
            "use_ddp": False,  # Use DistributedDataParallel
            "ddp_port": "10000",  # Port for Distributed Data Parallel communications
            "use_apex": True,  # Enable mix-precision with apex package
            "nb_gpu": torch.cuda.device_count(),
            "optimizer": {
                "class": Adam,
                "args": {
                    "lr": 0.0001,
                    "amsgrad": False,
                }
            },
`
Thanking in Advance sir

**Comment by FactoDeepLearning** [comment]
yes, they are.

**Comment by jjsr** [comment]
Thanks a lot sir
