### ISSUE TITLE
Resume Training from Last or best epoch ??

### ISSUE THREAD

**Issue by jjsr** [FactoDeepLearning/VerticalAttentionOCR#12]
Hello sir, I am in a clustered GPU environment, where GPu is shared among the various users of the cluster. Sir while training the models with default parameters, Training eventually stopped due to GPU constraints. Sir in this case I have 2 options at a particular time -1) Either resume training from best epoch till yet 2) Either resume training from last epoch ? . Sir it is also observed that there might be a huge difference between best and last epoch, for example, say best is 608th epoch and my last run epoch is 1500. So I wish to ask in this case when I resume my training should I start from the 608th epoch (best epoch) or 1500th  (last trained epoch) . Thanking you in advance sir

**Comment by FactoDeepLearning** [comment]
To continue your training, load last epoch. Loading best epoch is for evaluation time.

**Comment by jjsr** [comment]
Sir On this note I would also like to ask - there are 2 versions of Apex in Nvidia site -1) first is with C++ compiler 2) is only python build . Sir which of the above 2 you have used while doing your work ?? Since training is not progressing from my end it may be possible due to apex ? Any comment on that sir ?? Just to make sure -
1) pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
2) pip install -v --disable-pip-version-check --no-cache-dir ./ (I am using this and program is running fine)

Sir which above 2 installation types have you used sir ?? Will it matter while training ?? Sorry for troubling you sir
