### ISSUE TITLE
Recreating Results on IAM Line Level During Training from Scratch

### ISSUE THREAD

**Issue by miranghimire** [FactoDeepLearning/VerticalAttentionOCR#17]
Hi, I am currently training the model on the line level on IAM dataset but couldn't reproduce the results i.e CER 3.37% and WER 11.52% on val set. However, the weights from pre-trained model seems to reproduce the results. 
Do I need to change some hyperparameters to reproduce the results from scratch as well?

**Comment by FactoDeepLearning** [comment]
Hi, how long did you train the model, and what are your current results ?

**Comment by miranghimire** [comment]
I trained the model for 5000 epochs; Best result was obtained 4890 which is 4.34% CER and 14.5% WER on val set

**Comment by FactoDeepLearning** [comment]
Hyperparameters seem fine... This may be due to changes from one configuration to another (pytorch/cuda version), but the difference is relatively high

**Comment by miranghimire** [comment]
I went through the pre-trained model and amsgrad flag of Adam optimizer was False while in code it is True. I turned off the amsgrad and re-ran the code; result is very very close to what is reported.

**Comment by FactoDeepLearning** [comment]
Thank you very much for your feedback, it makes sense, I corrected the mistake.
