### ISSUE TITLE
IAM dataset does not have train.xml

### ISSUE THREAD

**Issue by sharmaannapurna** [FactoDeepLearning/VerticalAttentionOCR#3]
Hi, 
Thank you for sharing the code for experiments. I try to follow the steps mentioned in the readme file. 

File "Datasets/format_datasets.py", line 98, in format_IAM_paragraph
    xml_root = ET.parse(xml_path).getroot()

The final error says no train.xml file or directory exists.
Please show some pointers. Thanks in advance.

**Comment by FactoDeepLearning** [comment]
Hi,
Can you check that train.xml, valid.xml and test.xml are in the folder Datasets/raw/IAM with the .tgz files you downloaded (from IAM source). You might have removed them or change the dataset location.

**Comment by sharmaannapurna** [comment]
Oh Yes...I have redirected to my already downloaded dataset. Thank you.
