### ISSUE TITLE
Visual Assessment

### ISSUE THREAD

**Issue by rzamarefat** [FactoDeepLearning/VerticalAttentionOCR#6]
Hello, Thank you for your great work and also open-sourcing this implementation. I was wondering if you could instruct me for getting any visual assessment on the pre-trained weights that you have provided in the repo. That is, I want to give an image to the model and see the string outputs of text residing in the image. How can I do that?

**Comment by FactoDeepLearning** [comment]
Hi,

I am not sure what you mean by visual assessment but if I understand you well you could project the computed attention weights at each step on the input image to check that the focus is correctly on the lines (using matplotlib for example).

For the prediction, if it's just a test, the simplest way is to replace the first image in an already formatted dataset, let's say RIMES (valid_0.png). You can then call model.evaluate("RIMES-valid") in the main script and print the result in the compute_metrics function (from trainer_pg_va.py).
For a cleaner implementation, you should load your image in a tensor, and then look at generic_dataset_manager.py to apply the different formatting instruction (normalization, dpi, etc...) then give it as input of the model (as in evaluate_batch) and convert the prediction into string (as in compute_metrics).

**Comment by rzamarefat** [comment]
I think you got what I wanted to say correctly. I want to give some images containing lines or paragraphs to the model and see the result of the OCR. As simple as that. This is what I mean by visual assessment. 
I have done what you instructed me to do so. In other words I call model.evaluate() but unfortunately I don't know what should be the arg of this method. I tried absolute path of an image and also "RIMES" and "RIMES-valid" but got key error.

**Comment by FactoDeepLearning** [comment]
The key must match one of the keys you set in the main file: params["dataset_params"]["valid"].

**Comment by rzamarefat** [comment]
pred = model.evaluate(params["dataset_params"]["valid"])
Is this correct? I have written this in main module.

**Comment by FactoDeepLearning** [comment]
If you haven't modify the main, params["dataset_params"]["valid"] is a dict whose only item key is "dataset_name-valid" where dataset_name can be IAM, RIMES, etc... So depending on which dataset_name you set, you should have:
```
def train_and_test(rank, params):
    params["training_params"]["ddp_rank"] = rank
    model = Manager(params)
    metrics = model.evaluate("dataset_name-valid")
```
