### ISSUE TITLE
Data Preprocess

### ISSUE THREAD

**Issue by yusirhhh** [FactoDeepLearning/VerticalAttentionOCR#8]
Hello, thank you very much for this outstanding work. But I am a little bit confused and hope to get your help.
I found that the read image is not normalized to [-1,1] like the traditional method. It is [0,255]. Does this operation have any special meaning?

**Comment by FactoDeepLearning** [comment]
Hello, we noted it just has insignificant impact on the final results. You can, or not, normalize the input for the proposed approach without issue.
