### ISSUE TITLE
Regarding Low GPU Memory  and Apex error 

### ISSUE THREAD

**Issue by jjsr** [FactoDeepLearning/VerticalAttentionOCR#9]
Hello sir my gpu memory is 16G. It is unable to process minbatch =8 but able to process minbatch=4 . any values higher than 4 gives CUDA out pf memory error  ?? What may be changes should I do to run it on with minbatch 4 without affecting the result ? and apart from that sir there is no apex 0.1.0  in pypi ? How have you compiled apex sir

**Comment by FactoDeepLearning** [comment]
Hello, I think there is no way for you without affecting the results except from using the automatic mixed precision with apex. 
You should follow the quick start section from https://github.com/NVIDIA/apex

**Comment by jjsr** [comment]
Thanks a lot sir. I am able to configure apex, But sir I am on 54th epoch still Best epoch is 0th epoch with CER 0.92 is it the expected results. In the earlier closed issue I am able to see there was an important line missing . Thanks again for the wonderful work and prompt reply sir .  After Apex I am able to run it on GPU.

**Comment by FactoDeepLearning** [comment]
It seems right if you are training the model from scratch, I invite you to refer to the associated paper (link in readme file) for training curve tendency.

**Comment by jjsr** [comment]
Yes sure sir. Thanks alot
